# TypeProf 0.21.11

# Classes
module Rbmk
  VERSION: String

  def execute_file: (String file, *String args) -> bool?
  def self.execute_file: (String file, *String args) -> bool?
  def transpile_file: (String file) -> untyped
  def self.transpile_file: (String file) -> untyped
  def transpile: (String src) -> String
  def self.transpile: (String src) -> String
  def execute_rb_file: (String file, *String args) -> bool?
  def self.execute_rb_file: (String file, *String args) -> bool?
  def rb_path: (String path) -> untyped
  def self.rb_path: (String path) -> untyped

  class Error < StandardError
  end

  class CLI < Thor
    def exec: (*String args) -> bool?
  end
end
